using NReact;
using System.Linq;
using System.Windows.Controls;

namespace ToDoApp1
{
	using static NFactory;

	class TodoList : NClass
	{
		#region must be autogenerated from CSX

		public string[] Items
		{
			get
			{
				return Get(NFactory.Properties.Items, default(string[]));
			}
			set
			{
				Set(NFactory.Properties.Items, value);
			}
		}

		public override NElement Render()
		{
			return new NXaml<StackPanel>().
						  Children(Items.Map((i, idx) => new TodoItem(i)));
		} 

		#endregion

		public TodoList()
		{
			Items = new string[0];
		}
	}
}